apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
    flags:
      disableValidation: true
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: notional-buffer-347815
  artifacts: 
    - image: us.gcr.io/notional-buffer-347815/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: "src/**/*.ts"
            dest: .
